/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122942-gc7b5f1537d-20260222"
#endif /* AVUTIL_FFVERSION_H */
